(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h,k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},n;if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var q={a:!0},r={};try{r.__proto__=q;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=n;function u(a){return!(a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED)};function v(a){var b=void 0===b?null:b;var c=document.createEvent("CustomEvent");c.initCustomEvent("gwdfontsloaded",!0,!0,b);a.dispatchEvent(c)};function x(){var a=HTMLElement.call(this)||this;a.j=[];a.g=null;a.s=a.m.bind(a,!0);a.o=a.m.bind(a,!1);a.i=null;a.h=null;return a}var y=HTMLElement;x.prototype=k(y.prototype);x.prototype.constructor=x;if(t)t(x,y);else for(var z in y)if("prototype"!=z)if(Object.defineProperties){var A=Object.getOwnPropertyDescriptor(y,z);A&&Object.defineProperty(x,z,A)}else x[z]=y[z];h=x.prototype;h.disconnectedCallback=function(){C(this)};
h.startDynamicFontLoading=function(){this.g&&(C(this),this.g.parentElement.removeChild(this.g),this.g=null);this.j=[];this.i=null};
h.parseFontList=function(a){if(void 0!=a){a=a.trim();for(var b="",c=0,e=!1,d=0;d<a.length;d++)if('"'==a[d]&&(e=!e),!(e||","!=a[d]&&d!=a.length-1)){c=a.substring(c,","==a[d]?d:d+1).trim();var f=c.indexOf("https://fonts.googleapis.com/css?family=");if(0==f||1==f){'"'==c[0]&&'"'==c[c.length-1]?this.j.push(c.substring(1,c.length-1)):this.j.push(c);f+=40;var g=c.indexOf(":",f);-1==g&&(g='"'==c[c.length-1]?c.length-1:c.length);c=c.substring(f,g);c=c.length?'"'+c.replace(/[+]/g," ")+'"':""}c&&(0<b.length&&
(b+=", "),b+=c);c=d+1}return b}};
h.endDynamicFontLoading=function(){var a=this.ownerDocument;if(!a)return!0;for(var b=D(a),c=E(this.j),e=Object.keys(c),d=0;d<e.length;d++){for(var f=e[d],g=c[f],l=b[f]||{},m=Object.keys(g),w=0;w<m.length;w++){var B=m[w];l[B]&&delete g[B]}0==Object.keys(g).length&&delete c[f]}e=Object.keys(c).sort();if(0==e.length)return!0;b="";for(d=0;d<e.length;d++)f=e[d],g=Object.keys(c[f]).sort(),l=g.indexOf("default"),-1<l&&(0<b.length&&(b+="|"),b+=f,g.splice(l,1)),0<g.length&&(0<b.length&&(b+="|"),b+=f+":"+g.join(","));
this.g=a.createElement("link");this.g.setAttribute("rel","stylesheet");this.g.setAttribute("type","text/css");this.g.setAttribute("href","https://fonts.googleapis.com/css?family="+b);this.ownerDocument.fonts&&this.ownerDocument.fonts.load?(this.i=e.map(function(F){return'"'+F.replace(/[+]/g," ")+'"'}),this.g.addEventListener("load",this.s,!1),this.g.addEventListener("error",this.o,!1)):G(this,e);a.head.insertBefore(this.g,a.head.querySelector("style"));return!1};
function D(a){a=Array.prototype.slice.call(a.querySelectorAll('link[href^="https://fonts.googleapis.com/css?family="]')).map(function(b){return b.getAttribute("href")});return E(a)}function E(a){for(var b={},c=0;c<a.length;c++)for(var e=a[c].substring(40).split("|"),d=0;d<e.length;d++){var f=e[d].indexOf(":"),g=-1==f?e[d]:e[d].substring(0,f),l=b[g]||{};if(-1==f||f==e[d].length-1)l["default"]=!0;else{f=e[d].substring(f+1).split(",");for(var m=0;m<f.length;m++)l[f[m]]=!0}b[g]=l}return b}
h.m=function(a,b){if(u(this)&&this.g&&b.target==this.g)if(C(this),a&&this.i&&0!=this.i.length){a=this.ownerDocument;b=Array.prototype.slice.call(this.i);for(var c=0;c<b.length;c++){var e=this.u.bind(this,b[c],this.i);a.fonts.load("12px "+b[c]).then(e,e)}}else v(this)};h.u=function(a,b){b==this.i&&(a=b.indexOf(a),-1!=a&&(b.splice(a,1),0==b.length&&v(this)))};
function G(a,b){a.h=[];for(var c=[],e=[],d=0;d<b.length;d++)for(var f=0;2>f;f++){var g=a.ownerDocument.createElement("div");g.className="gwdfontloaderprobe";g.textContent="Sample text";g.style.opacity=0;g.style.position="absolute";g.style.width="auto";g.style.height="auto";g.style.fontFamily='"'+b[d]+'",'+(0==f?"Arial":"Arial Black");a.ownerDocument.body.appendChild(g);a.h.push(g);c.push(g.offsetWidth);e.push(g.offsetHeight)}setTimeout(a.l.bind(a,c,e,0),50)}
h.l=function(a,b,c){if(u(this)&&this.h&&!this.h.some(function(f){return!u(f)})){for(var e=!0,d=0;d<this.h.length/2;d++)if(this.h[2*d].offsetWidth==a[2*d]&&this.h[2*d].offsetHeight==b[2*d]&&this.h[2*d+1].offsetWidth==a[2*d+1]&&this.h[2*d+1].offsetHeight==b[2*d+1]){e=!1;break}c++;e||40==c?(C(this),v(this)):setTimeout(this.l.bind(this,a,b,c),50)}};
function C(a){if(a.ownerDocument.fonts&&a.ownerDocument.fonts.load)a.g&&(a.g.removeEventListener("load",a.s,!1),a.g.removeEventListener("error",a.o,!1));else if(a.h){for(var b=0;b<a.h.length;b++){var c=a.h[b];u(c)&&c.parentElement.removeChild(c)}a.h=null}}customElements.define("gwd-font-loader",x);}).call(this);
